/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.controller.JogoController;
import br.ulbra.model.Jogo;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s.lucas
 */
public class FRPesquisajog extends javax.swing.JDialog {

    private FRCompararjog telaCompara;

    public void setTelaCompara(FRCompararjog telaCompara) {
        this.telaCompara = telaCompara;
    }

    private int produto;

    public void setProduto(int produto) {
        this.produto = produto;
    }

    /**
     * Creates new form FRPesquisajog
     */
    public FRPesquisajog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CaixaBuscaJog = new javax.swing.JTextField();
        BotãoBuscar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabelajog = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));

        CaixaBuscaJog.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        CaixaBuscaJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaBuscaJogActionPerformed(evt);
            }
        });
        CaixaBuscaJog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CaixaBuscaJogKeyPressed(evt);
            }
        });

        BotãoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/LUPA16.png"))); // NOI18N
        BotãoBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotãoBuscarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel1.setText("CONSULTAS JOGOS");

        Tabelajog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "PREÇO", "LOJA", "DATA LANÇAMENTO"
            }
        ));
        Tabelajog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelajogMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabelajog);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/controle.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CaixaBuscaJog, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(BotãoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CaixaBuscaJog, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotãoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /*private void pesquisar_jogo() {
        DefaultTableModel modelo = (DefaultTableModel) Tabelajog.getModel();
        modelo.setNumRows(0);
        JogoController controller = new JogoController();
        for (Jogo jog : controller.readForDesc(CaixaFiltro.getSelectedIndex(), CaixaBusca.getText())) {
            Object[] linha = {jog.getPkusuario(),
                jog.getNomeJog(),
                jog.getImageJog(),
                jog.getPrecoJog(),
                jog.getFreteJog()};
            modelo.addRow(linha);
        }
    }*/
    private void CaixaBuscaJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaBuscaJogActionPerformed

    }//GEN-LAST:event_CaixaBuscaJogActionPerformed

    private void CaixaBuscaJogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CaixaBuscaJogKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pesquisarJogo();
        }
    }//GEN-LAST:event_CaixaBuscaJogKeyPressed
    private void pesquisarJogo() {
        DefaultTableModel modelo = (DefaultTableModel) Tabelajog.getModel();
        modelo.setNumRows(0);
        JogoController controller = new JogoController();
        for (Jogo jog : controller.readDescJogo(CaixaBuscaJog.getText())) {
            Object[] linha = {jog.getPkjogo(),
                jog.getNomejog(),
                jog.getPrecojog(),
                jog.getLojajog(),
                jog.getDescricaojog()};
            modelo.addRow(linha);
        }
    }
    private void BotãoBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotãoBuscarMouseClicked
        pesquisarJogo();
    }//GEN-LAST:event_BotãoBuscarMouseClicked

    private void TabelajogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelajogMouseClicked
        if (Tabelajog.getSelectedRow() != -1) {
            if (produto == 1) {
                telaCompara.caixaCódigo1.setText(Tabelajog.getValueAt(Tabelajog.getSelectedRow(), 0).toString());
            } else if (produto == 2) {
                telaCompara.caixaCódigo2.setText(Tabelajog.getValueAt(Tabelajog.getSelectedRow(), 0).toString());
            }
            telaCompara.CarregarProduto(produto);
            this.dispose();
        };
    }//GEN-LAST:event_TabelajogMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRPesquisajog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRPesquisajog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRPesquisajog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRPesquisajog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRPesquisajog dialog = new FRPesquisajog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotãoBuscar;
    private javax.swing.JTextField CaixaBuscaJog;
    private javax.swing.JTable Tabelajog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
